// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src_proto/window.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "src_proto/window.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocol {

namespace {

const ::google::protobuf::Descriptor* Window_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Window_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_src_5fproto_2fwindow_2eproto() {
  protobuf_AddDesc_src_5fproto_2fwindow_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "src_proto/window.proto");
  GOOGLE_CHECK(file != NULL);
  Window_descriptor_ = file->message_type(0);
  static const int Window_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Window, fullscreen_),
  };
  Window_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Window_descriptor_,
      Window::default_instance_,
      Window_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Window, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Window, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Window));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_src_5fproto_2fwindow_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Window_descriptor_, &Window::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_src_5fproto_2fwindow_2eproto() {
  delete Window::default_instance_;
  delete Window_reflection_;
}

void protobuf_AddDesc_src_5fproto_2fwindow_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026src_proto/window.proto\022\010protocol\"\034\n\006Wi"
    "ndow\022\022\n\nfullscreen\030\001 \002(\010", 64);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "src_proto/window.proto", &protobuf_RegisterTypes);
  Window::default_instance_ = new Window();
  Window::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_src_5fproto_2fwindow_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_src_5fproto_2fwindow_2eproto {
  StaticDescriptorInitializer_src_5fproto_2fwindow_2eproto() {
    protobuf_AddDesc_src_5fproto_2fwindow_2eproto();
  }
} static_descriptor_initializer_src_5fproto_2fwindow_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Window::kFullscreenFieldNumber;
#endif  // !_MSC_VER

Window::Window()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.Window)
}

void Window::InitAsDefaultInstance() {
}

Window::Window(const Window& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.Window)
}

void Window::SharedCtor() {
  _cached_size_ = 0;
  fullscreen_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Window::~Window() {
  // @@protoc_insertion_point(destructor:protocol.Window)
  SharedDtor();
}

void Window::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Window::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Window::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Window_descriptor_;
}

const Window& Window::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_src_5fproto_2fwindow_2eproto();
  return *default_instance_;
}

Window* Window::default_instance_ = NULL;

Window* Window::New() const {
  return new Window;
}

void Window::Clear() {
  fullscreen_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Window::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.Window)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool fullscreen = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &fullscreen_)));
          set_has_fullscreen();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.Window)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.Window)
  return false;
#undef DO_
}

void Window::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.Window)
  // required bool fullscreen = 1;
  if (has_fullscreen()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->fullscreen(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.Window)
}

::google::protobuf::uint8* Window::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.Window)
  // required bool fullscreen = 1;
  if (has_fullscreen()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->fullscreen(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.Window)
  return target;
}

int Window::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool fullscreen = 1;
    if (has_fullscreen()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Window::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Window* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Window*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Window::MergeFrom(const Window& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_fullscreen()) {
      set_fullscreen(from.fullscreen());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Window::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Window::CopyFrom(const Window& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Window::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Window::Swap(Window* other) {
  if (other != this) {
    std::swap(fullscreen_, other->fullscreen_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Window::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Window_descriptor_;
  metadata.reflection = Window_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)
