// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src_proto/window.proto

#ifndef PROTOBUF_src_5fproto_2fwindow_2eproto__INCLUDED
#define PROTOBUF_src_5fproto_2fwindow_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_src_5fproto_2fwindow_2eproto();
void protobuf_AssignDesc_src_5fproto_2fwindow_2eproto();
void protobuf_ShutdownFile_src_5fproto_2fwindow_2eproto();

class Window;

// ===================================================================

class Window : public ::google::protobuf::Message {
 public:
  Window();
  virtual ~Window();

  Window(const Window& from);

  inline Window& operator=(const Window& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Window& default_instance();

  void Swap(Window* other);

  // implements Message ----------------------------------------------

  Window* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Window& from);
  void MergeFrom(const Window& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool fullscreen = 1;
  inline bool has_fullscreen() const;
  inline void clear_fullscreen();
  static const int kFullscreenFieldNumber = 1;
  inline bool fullscreen() const;
  inline void set_fullscreen(bool value);

  // @@protoc_insertion_point(class_scope:protocol.Window)
 private:
  inline void set_has_fullscreen();
  inline void clear_has_fullscreen();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool fullscreen_;
  friend void  protobuf_AddDesc_src_5fproto_2fwindow_2eproto();
  friend void protobuf_AssignDesc_src_5fproto_2fwindow_2eproto();
  friend void protobuf_ShutdownFile_src_5fproto_2fwindow_2eproto();

  void InitAsDefaultInstance();
  static Window* default_instance_;
};
// ===================================================================


// ===================================================================

// Window

// required bool fullscreen = 1;
inline bool Window::has_fullscreen() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Window::set_has_fullscreen() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Window::clear_has_fullscreen() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Window::clear_fullscreen() {
  fullscreen_ = false;
  clear_has_fullscreen();
}
inline bool Window::fullscreen() const {
  // @@protoc_insertion_point(field_get:protocol.Window.fullscreen)
  return fullscreen_;
}
inline void Window::set_fullscreen(bool value) {
  set_has_fullscreen();
  fullscreen_ = value;
  // @@protoc_insertion_point(field_set:protocol.Window.fullscreen)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_src_5fproto_2fwindow_2eproto__INCLUDED
